set(HPM_CHIP_SERIES HPM6700)
set(HPM_CHIP_SELECT HPM6750)
set(HPM_BOARD_SELECT px4_fmu_v6xhpm_siyi)

set(HPM_SDK_PATH ${PX4_SOURCE_DIR}/platforms/nuttx/NuttX/nuttx/arch/risc-v/src/hpmicro/hpm_sdk)
include_directories(${HPM_SDK_PATH}/arch)
include_directories(${HPM_SDK_PATH}/arch/riscv/l1c)
include_directories(${HPM_SDK_PATH}/soc/${HPM_CHIP_SERIES}/${HPM_CHIP_SELECT})
include_directories(${HPM_SDK_PATH}/soc/${HPM_CHIP_SERIES}/${HPM_CHIP_SELECT}/boot)
include_directories(${HPM_SDK_PATH}/soc/${HPM_CHIP_SERIES}/ip)
include_directories(${HPM_SDK_PATH}/drivers/inc)
include_directories(${HPM_SDK_PATH}/boards/${HPM_BOARD_SELECT})
include_directories(${HPM_SDK_PATH}/components)
include_directories(${HPM_SDK_PATH}/components/adc)
include_directories(${HPM_SDK_PATH}/components/camera)
include_directories(${HPM_SDK_PATH}/components/camera/mt9m114)
include_directories(${HPM_SDK_PATH}/components/camera/ov5640)
include_directories(${HPM_SDK_PATH}/components/camera/ov7725)
include_directories(${HPM_SDK_PATH}/components/camera/sgtl5000)
include_directories(${HPM_SDK_PATH}/components/codec/wm8960)
include_directories(${HPM_SDK_PATH}/components/debug_console)
include_directories(${HPM_SDK_PATH}/components/dma_mgr)
include_directories(${HPM_SDK_PATH}/components/enet_phy)
include_directories(${HPM_SDK_PATH}/components/enet_phy/dp83848)
include_directories(${HPM_SDK_PATH}/components/enet_phy/dp83867)
include_directories(${HPM_SDK_PATH}/components/enet_phy/rtl8201)
include_directories(${HPM_SDK_PATH}/components/enet_phy/rtl8211)
include_directories(${HPM_SDK_PATH}/components/spi)
include_directories(${HPM_SDK_PATH}/components/uart_lin)
include_directories(${HPM_SDK_PATH})
